[project]
name = "async-graph-anomaly-detection-v3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "db-dtypes>=1.7.1",
    "google-cloud>=0.34.0",
    "google-cloud-bigquery>=3.45.1",
    "google-cloud-bigquery-storage>=2.41.0",
    "ipykernel>=7.3.0",
    "jinja2>=3.1.6",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "seaborn>=0.13.2",
    "xgboost>=3.4.1",
]
